name: hcm-vs-as-rnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4
  - r-pheatmap
  - r-ggplot2
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-enrichplot
  - bioconductor-org.hs.eg.db
  - bioconductor-annotationdbi
